### ISSUE TITLE
Security Token Execption

### ISSUE THREAD

**Issue by nicolarohde** [BrianHooper/cwu-cs-advising#2]
Not sure if this'll be an issue, but this is what the stack trace is:

Feb 25 22:56:13 cs-advising cwu-advising[20198]: System.InvalidOperationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: Th
Feb 25 22:56:13 cs-advising cwu-advising[20198]:    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperation
Feb 25 22:56:13 cs-advising cwu-advising[20198]:    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRev
Feb 25 22:56:13 cs-advising cwu-advising[20198]:    at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
Feb 25 22:56:13 cs-advising cwu-advising[20198]:    at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
Feb 25 22:56:13 cs-advising cwu-advising[20198]:    --- End of inner exception stack trace ---

**Comment by nicolarohde** [comment]
You can see the logs with "sudo systemctl status kestrel-advising.service" or "sudo journalctl -u kestrel-advising" on the server.
